```{r}
library(rdrop2)
library(tidyverse)
library(vroom)
library(cellpanelr)
```

```{r}
drop_auth()
```

```{r}
exp <- expression()
arr <- exp %>%
  arrange(gene_name)
```

```{r}
wide <- arr %>%
  pivot_wider(
    names_from = gene_name,
    values_from = rna_expression
  )
```

## Create local files

```{r}
saveRDS(exp, "exp_gzip.rds", compress = "gzip")
saveRDS(arr, "arr_gzip.rds", compress = "gzip")
saveRDS(wide, "wide_gzip.rds", compress = "gzip")

saveRDS(exp, "exp_bzip2.rds", compress = "bzip2")
saveRDS(arr, "arr_bzip2.rds", compress = "bzip2")
saveRDS(wide, "wide_bzip2.rds", compress = "bzip2")

saveRDS(exp, "exp_xz.rds", compress = "xz")
saveRDS(arr, "arr_xz.rds", compress = "xz")
saveRDS(wide, "wide_xz.rds", compress = "xz")

vroom_write(exp, "exp.tsv")
vroom_write(arr, "arr.tsv")
vroom_write(wide, "wide.tsv")

vroom_write(exp, "exp.tsv.gz")
vroom_write(arr, "arr.tsv.gz")
vroom_write(wide, "wide.tsv.gz")

vroom_write(exp, "exp.tsv.bz2")
vroom_write(arr, "arr.tsv.bz2")
vroom_write(wide, "wide.tsv.bz2")

vroom_write(exp, "exp.tsv.xz")
vroom_write(arr, "arr.tsv.xz")
vroom_write(wide, "wide.tsv.xz")
```

## Read speed

```{r}
system.time({
  test <- readRDS("wide_xz.rds") %>%
    pivot_longer(
      cols = -depmap_id,
      names_to = "gene_name",
      values_to = "rna_expression"
    )
})
```


```{r}
system.time({
  test <- readRDS("arr_xz.rds")
})
```

```{r}
system.time({
  test <- readRDS("wide_bzip2.rds") %>%
    pivot_longer(
      cols = -depmap_id,
      names_to = "gene_name",
      values_to = "rna_expression"
    )
})
```

```{r}
system.time({
  test <- vroom("wide.tsv.xz") %>%
    pivot_longer(
      cols = -depmap_id,
      names_to = "gene_name",
      values_to = "rna_expression"
    )
})
```

```{r}
system.time({
  test <- readRDS("exp_xz.rds")
})
```

```{r}
system.time({
  test <- readRDS("arr_bzip2.rds")
})
```

```{r}
system.time({
  test <- vroom("wide.tsv.bz2") %>%
    pivot_longer(
      cols = -depmap_id,
      names_to = "gene_name",
      values_to = "rna_expression"
    )
})
```

```{r}
system.time({
  test <- readRDS("wide_gzip.rds") %>%
    pivot_longer(
      cols = -depmap_id,
      names_to = "gene_name",
      values_to = "rna_expression"
    )
})
```

```{r}
system.time({
  test <- readRDS("exp_bzip2.rds")
})
```

```{r}
system.time({
  test <- readRDS("arr_gzip.rds")
})
```

```{r}
system.time({
  test <- vroom("arr.tsv.xz")
})
```

```{r}
system.time({
  test <- vroom("exp.tsv.xz")
})
```

```{r}
system.time({
  test <- vroom("arr.tsv.bz2")
})
```

```{r}
system.time({
  test <- vroom("arr.tsv.gz")
})
```

## Time downloading

```{r}
system.time({
  test <- readRDS(url("https://www.dropbox.com/s/v34nmncansnw3hu/wide_gzip.rds?dl=1")) %>%
    pivot_longer(
      cols = -depmap_id,
      names_to = "gene_name",
      values_to = "rna_expression"
    )
})
```

```{r}
system.time({
  test <- readRDS("~/Documents/r-projects/DepMap data/22Q1/expression.rds")
})
```

