```{r}
library(cellpanelr)
library(tidyverse)
```


```{r}
df <- read_tsv("~/Documents/r-projects/sample_data/RL1_sample.tsv") %>%
  add_ids("CellLine")
exp <- expression()
# genes <- exp$gene_name %>%
#   unique()
# 
# exp <- exp %>%
#   filter(gene_name %in% c(genes[1:1000], "IFITM1", "IFITM2", "IFITM3"))
```

```{r}
measure_angle <- function(x, y) {
  acos(sum(x * y) / (sqrt(sum(x * x)) * sqrt(sum(y * y)))) / pi * 180
}
```

```{r}
merged <- df %>%
  left_join(
    exp,
    by = "depmap_id",
    suffix = c("", ".depmap")
  )

fit <- merged %>%
  group_by(gene_name) %>%
  filter(!is.na(gene_name)) %>%
  summarise(
    spearman_rho = suppressWarnings(cor.test(
      x = AUC,
      y = rna_expression,
      na.action = na.omit(),
      method = "spearman"
    )) %>%
      pluck("estimate")
  )
  # summarise(
  #   model = cor.test(
  #     AUC,
  #     rna_expression,
  #     method = "spearman",
  #     na.action = stats::na.omit(),
  #     exact = FALSE
  #   ) %>%
  #     broom::tidy() %>%
  #     pull("estimate")
  # )

fit
```

```{r}
fit %>%
  arrange(desc(spearman_rho))
```

